[package]
name = "aom-roar"
version = "0.1.0"
license-file = "LICENSE"
description = "A Rust port of Alliance for Open Media's Open Audio Renderer (OAR)."
readme = "README.md"
repository = "https://github.com/AOMediaCodec/roar/"
# Rust edition and version are also specified in MODULE.bazel for bazel builds.
edition = "2024"
rust-version = "1.97.1"
categories = ["multimedia::audio"]
keywords = [
  "Alliance for Open Media",
  "ambisonic audio",
  "ambisonics",
  "AOM",
  "audio renderer",
  "audio rendering",
  "audio",
  "binaural",
  "channel-based audio",
  "IAMF",
  "Immersive Audio Model and Formats",
  "immersive audio",
  "scene-based audio",
  "spatial audio",
]

[dependencies]
log = "0.4"
realfft = "3.5.0"
rustfft = "6.4.1"

[dev-dependencies]
# The current crates.io version (0.14.3) is out of date.  Pull from git until a
# new version is released.
googletest = { git = "https://github.com/google/googletest-rust",
               rev = "75ba2198e83bd2e62785fa92e2bf28aa30591a67" }